# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command and `artifact-name` to assign a name to
# distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
#     artifact-name: corne_left_with_logging
#
---
include:
  - board: nice_nano_v2
<<<<<<< HEAD
    shield: kawvin_split89_dongle_display_dongle display_130_cat
    artifact-name: kawvin_split89_dongle_display_32_DongleWithCat
  - board: nice_nano_v2
    shield: kawvin_split89_dongle_display_left
    ##cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: kawvin_split89_dongle_display_32_Left
  - board: nice_nano_v2
    shield: kawvin_split89_dongle_display_right
    artifact-name: kawvin_split89_dongle_display_32_Right
  # - board: nice_nano_v2
  #   shield: kawvin_split89_dongle_display_left  display_091_drum
  #   cmake-args: -DCONFIG_ZMK_DISPLAY=y
  #   artifact-name: kawvin_split89_dongle_display_32_Left_central

  # # 【方案33】  dongle：有（display:猫咪-横向(128*64))，display：敲鼓-竖向(128*32) By Kawvin
  # - board: nice_nano_v2
  #   shield: kawvin_split89_dongle_display_dongle display_130_cat
  #   artifact-name: kawvin_split89_dongle_display_33_DongleWithCat
  # - board: nice_nano_v2
  #   shield: kawvin_split89_dongle_display_left display_091_drum
  #   artifact-name: kawvin_split89_dongle_display_33_LeftWithDrum
  # - board: nice_nano_v2
  #   shield: kawvin_split89_dongle_display_right
  #   artifact-name: kawvin_split89_dongle_display_33_Right

# # 四、【重置固件】 
  # - board: nice_nano_v2
  #   shield: settings_reset

  
=======
    shield: nano2test
>>>>>>> e793e0214a9851d79fd3c56826cacd655c54a398
