# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command and `artifact-name` to assign a name to
# distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
#     artifact-name: corne_left_with_logging
#
---
include:

# 一、【无dongle】，如果不使用display,在 left.conf 或 right.conf 进行关闭
  # # 【方案11】  dongle：无，display：系统自带-横向  或  关闭
  # - board: nice_nano_v2
  #   shield: kawvin_split89_left
  #   artifact-name: kawvin_split89_11_Left
  #   # 带display使用
  #   # artifact-name: kawvin_split89_11_LeftWithDefault
  # - board: nice_nano_v2
  #   shield: kawvin_split89_right
  #   artifact-name: kawvin_split89_11_Right

  # # 【方案12】  dongle：无，display：猫咪-横向(128*32)
  # - board: nice_nano_v2
  #   shield: kawvin_split89_left display_091_cat
  #   artifact-name: kawvin_split89_12_LeftWithCat
  # - board: nice_nano_v2
  #   shield: kawvin_split89_right
  #   artifact-name: kawvin_split89_12_Right
  
  # # 【方案13】  dongle：无，display：敲鼓-竖向(128*32) By Kawvin
  # - board: nice_nano_v2
  #   shield: kawvin_split89_left display_091_drum
  #   artifact-name: kawvin_split89_13_LeftWithDrum
  # - board: nice_nano_v2
  #   shield: kawvin_split89_right
  #   artifact-name: kawvin_split89_13_Right



# 二、【有dongle，不使用display】,在 dongle.conf 进行关闭
  # # 【方案31】  dongle：有（不使用display)，display：系统自带-横向  或  关闭
  # - board: nice_nano_v2
  #   shield: kawvin_split89_dongle_dongle
  #   artifact-name: kawvin_split89_dongle_21_Dongle
  # - board: nice_nano_v2
  #   shield: kawvin_split89_dongle_left
  #   # artifact-name: kawvin_split89_dongle_21_Left
  #   artifact-name: kawvin_split89_dongle_21_LeftWithDefault    # 带display使用
  # - board: nice_nano_v2
  #   shield: kawvin_split89_dongle_right
  #   artifact-name: kawvin_split89_dongle_21_Right

  # # 【方案22】  dongle：有（不使用display)，display：猫咪-横向(128*32)
  - board: nice_nano_v2
    shield: kawvin_split89_dongle_dongle
    artifact-name: kawvin_split89_dongle_22_Dongle
  - board: nice_nano_v2
    shield: kawvin_split89_dongle_left display_091_cat
    artifact-name: kawvin_split89_dongle_22_LeftWithCat
  - board: nice_nano_v2
    shield: kawvin_split89_dongle_right
    artifact-name: kawvin_split89_dongle_22_Right

  # # 【方案23】  dongle：有（不使用display)，display：敲鼓-竖向(128*32) By Kawvin
  # - board: nice_nano_v2
  #   shield: kawvin_split89_dongle_dongle
  #   artifact-name: kawvin_split89_dongle_23_Dongle
  # - board: nice_nano_v2
  #   shield: kawvin_split89_dongle_left display_091_drum
  #   artifact-name: kawvin_split89_dongle_23_LeftWithDrum
  # - board: nice_nano_v2
  #   shield: kawvin_split89_dongle_right
  #   artifact-name: kawvin_split89_dongle_23_Right

# 三、【有dongle，使用display】， 在 dongle.conf 进行打开，键盘不使用display
  # #【方案21】  dongle：有（display:系统自带-横向(128*64))，display：无
  # - board: nice_nano_v2
  #   shield: kawvin_split89_dongle_display_dongle
  # # 带display使用
  #   artifact-name: kawvin_split89_dongle_display_31_DongleWithDefault
  # - board: nice_nano_v2
  #   shield: kawvin_split89_dongle_display_left
  #   artifact-name: kawvin_split89_dongle_display_31_Left
  # - board: nice_nano_v2
  #   shield: kawvin_split89_dongle_display_right
  #   artifact-name: kawvin_split89_dongle_display_31_Right

  # # 【方案32】  dongle：有（display:猫咪-横向(128*64))，display：无,除了关闭conf外
  # - board: nice_nano_v2
  #   shield: kawvin_split89_dongle_display_dongle display_130_cat
  #   artifact-name: kawvin_split89_dongle_display_32_DongleWithCat
  # - board: nice_nano_v2
  #   shield: kawvin_split89_dongle_display_left
  #   artifact-name: kawvin_split89_dongle_display_32_Left
  # - board: nice_nano_v2
  #   shield: kawvin_split89_dongle_display_right
  #   artifact-name: kawvin_split89_dongle_display_32_Right

  # 【方案33】  dongle：有（display:猫咪-横向(128*64))，display：敲鼓-竖向(128*32) By Kawvin
  # - board: nice_nano_v2
  #   shield: kawvin_split89_dongle_display_dongle display_130_cat
  #   artifact-name: kawvin_split89_dongle_display_32_DongleWithCat
  # - board: nice_nano_v2
  #   shield: kawvin_split89_dongle_display_left display_091_drum
  #   artifact-name: kawvin_split89_dongle_display_32_LeftWithDrum
  # - board: nice_nano_v2
  #   shield: kawvin_split89_dongle_display_right
  #   artifact-name: kawvin_split89_dongle_display_32_Right


  